interface SupportTicketData {
  ticketId: string
  customerName: string
  customerEmail: string
  issueSummary: string
  chatHistory: string
}

export async function sendSupportTicketEmail(data: SupportTicketData): Promise<boolean> {
  const { ticketId, customerName, customerEmail, issueSummary, chatHistory } = data

  const subject = `New Support Ticket: ${ticketId} - From ${customerName}`

  const emailBody = `
A new support ticket has been created by the AI Assistant, Flaggy.

---
Ticket Information:
---
- Ticket ID: ${ticketId}
- Date: ${new Date().toLocaleString()}

---
Customer Details:
---
- Name: ${customerName}
- Email: ${customerEmail}

---
Customer's Issue:
---
${issueSummary}

---
Chat Transcript:
---
${chatHistory}

---
Action Required:
---
Please respond to the customer at their provided email address: ${customerEmail}

This ticket was automatically generated by Flaggy AI Assistant.
`.trim()

  try {
    const emailServiceUrl = process.env.EMAIL_SERVICE_URL
    const emailApiKey = process.env.EMAIL_API_KEY
    const supportEmail = process.env.SUPPORT_EMAIL || "support@atlanticflagpole.com"

    if (!emailServiceUrl || !emailApiKey) {
      console.warn("[v0] Email service not configured. Logging ticket instead:")
      console.log("=".repeat(80))
      console.log("SUPPORT TICKET EMAIL")
      console.log("=".repeat(80))
      console.log(`To: ${supportEmail}`)
      console.log(`Subject: ${subject}`)
      console.log("-".repeat(80))
      console.log(emailBody)
      console.log("=".repeat(80))

      // Return true for development/testing purposes
      return true
    }

    const response = await fetch(emailServiceUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${emailApiKey}`,
      },
      body: JSON.stringify({
        to: supportEmail,
        from: "flaggy@atlanticflagpole.com",
        replyTo: customerEmail,
        subject,
        text: emailBody,
        html: formatEmailHtml(data),
      }),
    })

    if (!response.ok) {
      console.error("[v0] Failed to send email:", await response.text())
      return false
    }

    console.log(`[v0] Support ticket email sent successfully: ${ticketId}`)
    return true
  } catch (error) {
    console.error("[v0] Error sending support ticket email:", error)
    return false
  }
}

function formatEmailHtml(data: SupportTicketData): string {
  const { ticketId, customerName, customerEmail, issueSummary, chatHistory } = data

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Support Ticket ${ticketId}</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
  <div style="background: linear-gradient(135deg, #0B1C2C 0%, #1a2d3f 100%); color: white; padding: 30px; border-radius: 10px 10px 0 0; text-align: center;">
    <h1 style="margin: 0; font-size: 24px;">🚩 New Support Ticket</h1>
    <p style="margin: 10px 0 0 0; font-size: 14px; opacity: 0.9;">Created by Flaggy AI Assistant</p>
  </div>
  
  <div style="background: #f9f9f9; padding: 30px; border: 1px solid #e0e0e0; border-top: none;">
    <div style="background: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; border-left: 4px solid #C8A55C;">
      <h2 style="margin: 0 0 15px 0; color: #0B1C2C; font-size: 18px;">📋 Ticket Information</h2>
      <p style="margin: 5px 0;"><strong>Ticket ID:</strong> <span style="color: #C8A55C; font-weight: bold;">${ticketId}</span></p>
      <p style="margin: 5px 0;"><strong>Date:</strong> ${new Date().toLocaleString()}</p>
    </div>

    <div style="background: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; border-left: 4px solid #4A90E2;">
      <h2 style="margin: 0 0 15px 0; color: #0B1C2C; font-size: 18px;">👤 Customer Details</h2>
      <p style="margin: 5px 0;"><strong>Name:</strong> ${customerName}</p>
      <p style="margin: 5px 0;"><strong>Email:</strong> <a href="mailto:${customerEmail}" style="color: #4A90E2; text-decoration: none;">${customerEmail}</a></p>
    </div>

    <div style="background: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; border-left: 4px solid #E74C3C;">
      <h2 style="margin: 0 0 15px 0; color: #0B1C2C; font-size: 18px;">❗ Customer's Issue</h2>
      <p style="margin: 0; white-space: pre-wrap;">${issueSummary}</p>
    </div>

    <div style="background: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; border-left: 4px solid #95A5A6;">
      <h2 style="margin: 0 0 15px 0; color: #0B1C2C; font-size: 18px;">💬 Chat Transcript</h2>
      <div style="background: #f5f5f5; padding: 15px; border-radius: 5px; font-family: monospace; font-size: 13px; white-space: pre-wrap; max-height: 300px; overflow-y: auto;">${chatHistory}</div>
    </div>

    <div style="background: #FFF3CD; padding: 20px; border-radius: 8px; border-left: 4px solid #FFC107;">
      <h2 style="margin: 0 0 10px 0; color: #856404; font-size: 18px;">⚡ Action Required</h2>
      <p style="margin: 0; color: #856404;">Please respond to the customer at their provided email address: <strong>${customerEmail}</strong></p>
    </div>

    <div style="text-align: center; margin-top: 30px; padding-top: 20px; border-top: 2px solid #e0e0e0;">
      <a href="mailto:${customerEmail}?subject=Re: Support Ticket ${ticketId}" style="display: inline-block; background: #C8A55C; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; font-weight: bold;">Reply to Customer</a>
    </div>
  </div>

  <div style="background: #0B1C2C; color: white; padding: 20px; text-align: center; border-radius: 0 0 10px 10px; font-size: 12px;">
    <p style="margin: 0;">This ticket was automatically generated by <strong>Flaggy AI Assistant</strong></p>
    <p style="margin: 5px 0 0 0; opacity: 0.7;">Atlantic Flagpole Support System</p>
  </div>
</body>
</html>
  `.trim()
}
